config/routes.rb
Rails.application.routes.draw do
  #get 'errors/file_not_found'

  #get 'errors/unprocessable'

  #get 'errors/internal_server_error'

  resources :conversations do 
    resources :messages, only: [:index, :create]
  end
  
  
  resources :offers

  root 'communities#show'

  get '/offers/:id/rejected', :to => 'offers#rejected', as: :offer_rejected
  get '/offers/:id/accepted', :to => 'offers#accepted', as: :offer_accepted
  get '/offers/:id/confirm', :to => 'offers#confirm', as: :offer_confirm

  get '/auth/:provider/callback' => 'users#venmo'
  get '/auth/venmo', as: 'venmo_login'


  get '/communities/search', as: :search
  get '/communities/info', as: :info
  post '/communities/search' => 'communities#set', as: :set

  post '/items' => 'items#search'

  resources :communities do 
    resources :items
  end

  resources :users do
    resources :offers, only: [:index]
    resources :items do 
      resources :offers, only: [:new]
    end
  end

  get '/users/:id/offers/sent' => 'offers#sent', as: :offers_sent
  get '/users/:id/offers/received' => 'offers#received', as: :offers_received

  delete '/users/:user_id/items/:id', to: 'items#destroy', as: :delete_item
  patch '/users/:id' => 'users#update'
  get '/signup' => 'users#new'

  get '/logout', to: 'sessions#destroy', as: :logout
  get '/login', to: 'sessions#new', as: :login
  post '/login' => 'sessions#create'

  get '/about' => 'static_pages#about', as: :about


  #match '/404', to: 'errors#file_not_found', via: :all
  #match '/422', to: 'errors#unprocessable', via: :all
  #match '/500', to: 'errors#internal_server_error', via: :all

end

app/models/user.rb
class User < ActiveRecord::Base
  #acts_as_messageable
  attr_accessor :delete_avatar
  attr_encrypted :token, :key => ENV['encrypt_key']
  belongs_to :community
  has_many :items, :foreign_key => 'seller_id'
  has_many :offers_sent, :class_name => "Offer", :foreign_key => 'buyer_id'
  has_many :conversations, :foreign_key => 'user1_id'
  has_many :conversations, :foreign_key => 'user2_id'
  validates :name, presence: true, format: { 
    with: /\A[a-zA-Z\s]+\z/,
    message: "only allows letters and spaces"
  }

  validates :email, presence: true, format: {
    with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i,
    message: "must be proper email format"
  }
  
  has_secure_password

  before_validation {avatar.clear if delete_avatar =='1'}

  has_attached_file :avatar, 
                    :styles => { :medium => "300x300#", 
                                 :thumb => "100x100#" },
                    :default_url => 'placeholder-avatar.png'
                    # :storage => :s3,
                    # :s3_permissions => "public-read",
                  # :path => ":filename",
                    #   :bucket => ENV['amazon_bucket'],
                    # :s3_credentials => {
                    #   :access_key_id => ENV['amazon_access_key'],
                    #   :secret_access_key => ENV['amazon_secret'],
                    # }

                  #   :s3_permissions => "public-read",
                  # :path => ":filename",
                  # :bucket => ENV['amazon_bucket']

  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def conversations
    conversation_from_me = Conversation.where(:user1_id => self.id)
    conversation_for_me = Conversation.where(:user2_id => self.id)
    all_conversations_with_me = conversation_from_me + conversation_for_me
  end
  

  def has_venmo?
    self.venmo_id && self.encrypted_token
  end

  # def mailboxer_email(object)
  #   email
  # end

  def offers_sent
    Offer.all.select{ |offer| offer.buyer == self }
  end

  def pending_offers_sent
    Offer.all.select{ |offer| offer.buyer == self && offer.status == 'pending'}
  end

  def rejected_offers_sent
    Offer.all.select{ |offer| offer.buyer == self && offer.status == 'rejected'}
  end

  def accepted_offers_sent
    Offer.all.select{ |offer| offer.buyer == self && offer.status == 'accepted'}
  end
  
  def offers_received
    self.items.collect{|item| item.offers}.flatten
  end

  def pending_offers_received
    self.offers_received.select{ |offer| offer.status=="pending"}
  end

  def seller?
    !(self.items == [])
  end 

  def buyer?
    !(self.offers_sent == [])
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_community, only: :show
  
  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      community_valid = set_community
      if community_valid == nil 
        session[:user_id] = @user.id
        redirect_to search_path
      else 
        session[:user_id] = @user.id
        redirect_to root_path
      end 
      
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

      if ((params[:user][:password]== '')&&(params[:user][:new_password]== ''))
        @user.update_attributes(user_params)
        @user.save
        flash[:notice] = "Profile successfully updated"
        redirect_to user_path(@user)
      elsif !(params[:user][:new_password] ==  params[:user][:new_password_confirmation])
        flash[:notice] = "Passwords did not match"
        redirect_to edit_user_path @user
      elsif !(BCrypt::Password.new(current_user.password_digest) == params[:user][:password] )
        flash[:notice]  = "Old Password did not match"
        redirect_to edit_user_path @user
      elsif ((params[:user][:new_password] ==  params[:user][:new_password_confirmation]) && (BCrypt::Password.new(current_user.password_digest) == params[:user][:password]))
        @user.update_attributes(user_params)
        @user.password_digest = BCrypt::Password.create(params[:user][:new_password])
        @user.save
        flash[:notice] = "Profile successfully updated"
        redirect_to user_path(@user)
    end
  end

  def show
    @user = User.find(params[:id])
    if @user != current_user
      render :show_user
    end 
  end

  def show_user
  end 

  def destroy
    @user.avatar = nil
    @user.save
  end

  def venmo
    VenmoWrapper.new.authenticate_venmo(current_user,auth_hash)
    redirect_to user_path(current_user)
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :delete_avatar)
    end

    def set_community
      domain = @user.email.split("@")[1]
      community = find_community(domain)
      if community != nil
        @user.community = find_community(domain)
        @user.save
      else
        return nil 
      end 
    end 

    def find_community(domain)
      base_url = "https://raw.githubusercontent.com/Hipo/university-domains-list/master/world_universities_and_domains.json"
      response = Net::HTTP.get_response(URI.parse(base_url))
      data = response.body
      result = JSON.parse(data)
      result.each do |school|
        if school["domain"] == domain
          community = Community.find_by(name: school["name"])
          if community == nil 
            community = Community.create(name: school["name"])
          end 
          return community
        end 
      end 
      return nil
    end 

  def auth_hash
    request.env['omniauth.auth']
  end

  def check_community 
    unless current_user.community_id == User.find(params[:id]).community_id
      redirect_to root_path # halts request cycle
    end
  end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_carouselitem.html.erb
  <div class="owl-content"> 
    <div class="padd-15">
      <a href=<%= user_item_path(item.seller, :id => item.id)%>><img src="/assets/<%= item.product.url(:medium)  %>" alt=<%= item.name %> class="img-responsive"></a>
      <h4><a href=<%= user_item_path(item.seller, :id => item.id)%>> <%= item.name %> <span class="color pull-right">$<%= item.price %></span></a></h4>
      <div class="clearfix"></div>
    </div>
  </div>

app/views/users/_community_user.html.erb
<div class="col-md-3 col-sm-6">
  <!-- Team member -->
  <div class="team-member"> 
    <div class="t-container">
      <!-- Social -->
      <div class="social brand-bg">
        <a class="facebook" href="/users/<%= user.id %>"><i class="fa fa-user circle-3"></i></a>
      </div>
      <!-- Image -->
      <%= image_tag user.avatar.url(:medium), :class => "img-responsive center-block"%>
    </div>
    <!-- Name -->
    <h4> <%= link_to(user.name, user_path(current_user, :id => user.id)) %> </h4>
    <p>Items Selling: <%= user.items.count %></p>
  </div>
</div>

app/views/users/edit.html.erb
<div class="main-block">

  <div class="page-heading-two">
    <div class="container">
    <h2>Edit Account <span>Campus Bazaar</span></h2>
      <div class="clearfix"></div>
    </div>
  </div>

  <div class="container"> 
    <div class="ecommerce">
      <div class="row">
        <div class="col-md-9 col-sm-8 col-md-push-3 col-sm-push-4">
          <div class="shopping-content">
            <h4><i class="fa fa-user color"></i>&nbsp; <%= @user.name %>&nbsp;</h4>
            <hr>
            <div class="shopping-account">
              <div class="container"> 
                <%= form_for @user, :html => {:multipart => true} do |f| %>

                <div class="upload-preview">
                  <img/>
                  <%= f.label :avatar, class: 'control-label'%>  
                  <%= f.file_field :avatar, class: 'form_field file' %>
                </div>

                <div class="form-group">
                  <%= f.label :delete_avatar%>
                  <%= f.check_box(:delete_avatar)%><br>
                </div>

                <div class="form-group">
                <%= f.label :name,  class: "col-md-4" %>
                <%= f.text_field :name, class: 'form-control col-md-6', style: "max-width:300px;",:placeholder => @user.name %><br />
                </div>

                <div class="form-group">
                <%= f.label :email,  class: "col-md-4" %>
                <%= f.text_field :email, class: 'form-control col-md-6', style: "max-width:300px;",:placeholder => @user.email %><br />
                </div>

                <div class="form-group">
                <%= f.label :old_password, class: 'control-label col-md-4' %>
                <%= f.password_field :password, class: 'form-control col-md-6', style: "max-width:300px;" %>
                </div>

                <div class="form-group">
                <%= f.label :new_password, class: 'control-label col-md-4'%>
                <%= f.password_field :new_password, class: 'form-control col-md-6', style: "max-width:300px;" %>
                </div>

                <div class="form-group">
                <%= f.label :new_password_confirmation, class: 'control-label col-md-4'%>
                <%= f.password_field :new_password_confirmation, class: 'form-control col-md-6', style: "max-width:300px;" %>
                </div>
                
                <div class="clearfix"></div>

                <div class="form-group">
                  <%= f.submit "Save Changes", class: "btn btn-primary" %>
                  <% end %>
                </div>

              </div>
            </div>
          </div>
        </div> <!--PUSH-4-->
        <div class="col-md-3 col-sm-4 col-md-pull-9 col-sm-pull-8">
          <div class="sidebar">
            <h2>Navigation</h2>
            <ul class="account-nav">
              <li><%= link_to "Edit Account", edit_user_path(current_user)%></li>
              <li><%= link_to  "Your Account", user_path(current_user) %></li>
              <li><%= link_to "Manage Items", user_items_path(current_user)%></li>
            </ul>
          </div>
        </div> <!--PULL-8-->
      </div> <!--ROW-->
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="page-heading-two">
  <div class="container">
    <h2>Signup!<span></span></h2>
    <div class="clearfix"></div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="center signup-center">
    <div class="">
      <div class="well login-reg-form">
      <%= form_for :user, url: '/users', :class => "form-horizontal", :type => "form" do |f| %>
        <div class="form-group">
        <% if @user && @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        </div>
        <!-- Form Group -->
        <div class="form-group <%= "error_field" if @user && @user.errors[:name] %>">
          <!-- Label -->
            <%= f.label :name, :class => "control-label"  %>
          <div class="">
            <!-- Input -->
            <% if @user && @user.errors[:name] %>
              <span><%= @user.errors[:name].first %></span>
            <% end %>
            <%= f.text_field :name, :class => 'form-control', :type => "text" %>
          </div>
        </div>

        <div class="form-group <%= "error_field" if @user && @user.errors[:email] %>">
          <!-- Label -->
            <%= f.label :email, :class => "control-label"  %>
          <div class="">
            <!-- Input -->
            <% if @user && @user.errors[:email] %>
              <span><%= @user.errors[:email].first %></span>
            <% end %>
            <%= f.text_field :email, :class => 'form-control', :type => "text" %>
          </div>
        </div>

        <div class="form-group <%= "error_field" if @user && @user.errors[:password] %>">
          <!-- Label -->
            <%= f.label :password, :class => " control-label" %>
          <div class="">
            <!-- Input -->
            <% if @user && @user.errors[:password] %>
              <span><%= @user.errors[:password].first %></span>
            <% end %>
            <%= f.password_field :password, :class => 'form-control' %>
          </div>
        </div>

        <div class="form-group <%= "error_field" if @user && @user.errors[:password] %>">
          <!-- Label -->
            <%= f.label :password_confirmation, :class => "control-label" %>
          <div class="">
            <!-- Input -->
            <%= f.password_field :password_confirmation, :class => 'form-control'%>
          </div>
        </div>


        <div class="form-group">
          <div class="">
            <!-- Button -->
            <%= f.submit "Submit", :class => "btn btn-red" %>
          </div>
        </div>
      <% end %>
      </div>
      </div>
    </div>
  </div>
  <br><br><br><br>
</div>

app/views/users/show.html.erb
<div class="main-block">

  <div class="page-heading-two">
    <div class="container">
      <h2>My Account <span>Campus Bazaar</span></h2>
      <div class="breads">
        Home / <a href="#">Page</a> / <a href="#">Sub Page</a>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>

  <div class="container"> 
    <div class="ecommerce">
      <div class="row">
        <div class="col-md-9 col-sm-8 col-md-push-3 col-sm-push-4">
          <div class="shopping-content">
            <h4><i class="fa fa-user color"></i>&nbsp; My Account&nbsp;<small>Campus Bazaar</small></h4>
            <hr>
            <div class="shopping-account">
              <div class="row"> 
                <div class="col-md-3 col-sm-4 col-xs-4">
                  <!-- Image -->
                  <%#= image_tag @user.avatar.url(:medium) %>
                  <img src="<%= @user.avatar.url(:medium) %>" class="img-responsive img-thumbnail" alt="<%= @user.name%> profile picture">
                </div>
                <div class="col-md-9 col-sm-8 col-xs-8">
                  <!-- Your Name / Heading -->
                  <h4><%= @user.name %></h4>
                  <div class="address">
                    <!-- Email Address -->
                    <span><i class="fa fa-envelope color"></i>&nbsp; <%= @user.email %></span><br>
                    <span><i class="fa fa-cubes color"></i>&nbsp; <%= @user.items.count%> items for sale</span><br>
                    <span><i class="fa fa-money color"></i>&nbsp; <%= @user.pending_offers_received.count %> offers pending</span>
                  </div>
                </div> 
                <% unless @user.has_venmo? %>
                  <%= link_to 'Log in with Venmo', venmo_login_path %>
                <% end %>
              </div>
            </div>
          </div>
        </div> <!--PUSH-4-->
        <div class="col-md-3 col-sm-4 col-md-pull-9 col-sm-pull-8">
          <div class="sidebar">
            <h2>Navigation</h2>
            <ul class="account-nav">
              <li><%= link_to  "Your Account", user_path(current_user) %></li>
              <li><%= link_to "Edit Account", edit_user_path(current_user)%></li>
              <li><%= link_to "Manage Items", user_items_path(current_user)%></li>
            </ul>
          </div>
        </div> <!--PULL-8-->
      </div> <!--ROW-->
    </div>
  </div>
</div>
          

app/views/users/show_user.html.erb
  <div class="page-heading-two">
    <div class="container">
      <h2>Profile <span>Campus Bazaar</span></h2>
      <div class="clearfix"></div>
    </div>
  </div>

  <div class="container"> 
    <div class="ecommerce">
      <div class="row">
        <div class="col-md-9 col-sm-8 col-md-push-3 col-sm-push-4">
          <div class="shopping-content">
            <h4><i class="fa fa-user color"></i>&nbsp; Profile&nbsp;<small>Campus Bazaar</small></h4>
            <hr>
            <div class="shopping-account">
              <div class="row"> 
                <div class="col-md-3 col-sm-4 col-xs-4">
                  <!-- Image -->
                  <img src="<%= @user.avatar.url(:medium) %>" class="img-responsive img-thumbnail" alt="<%= @user.name%> profile picture">
                </div>
                <div class="col-md-9 col-sm-8 col-xs-8">
                  <!-- Your Name / Heading -->
                  <h4><%= @user.name %></h4>
                  <div class="address">
                    <!-- Email Address -->
                    <span><i class="fa fa-envelope color"></i>&nbsp; <%= @user.email %></span><br>
                    <span><i class="fa fa-cubes color"></i>&nbsp; <%= @user.items.count%> items for sale</span><br>
                    <span><i class="fa fa-money color"></i>&nbsp; <%= @user.pending_offers_received.count %> offers pending</span>
                  </div>
                </div> 
              </div>
            </div>
          </div>
        </div> <!--PUSH-4-->
        <div class="col-md-3 col-sm-4 col-md-pull-9 col-sm-pull-8">
          <div class="sidebar">
            <h2>Navigation</h2>
            <ul class="account-nav">
              <li><%= link_to  "Profile", user_path(@user) %></li>
            </ul>
          </div>
        </div> <!--PULL-8-->
      </div> <!--ROW-->
      <div class="recent-items">
        <!-- Block heading two -->
        <div class="block-heading-two">
          <h3><span>Recent Items</span></h3>
        </div>
        <!-- Owl carousel block starts -->
        <!-- Change values of data-items, data-auto-play, data-pagination & data-single-item based on your needs -->
          <div class="owl-carousel owl-theme" data-items="<%= @user.items.count %>" data-auto-play="true" data-pagination="true" data-single-item="false" style="opacity: 1; display: block;">
            <!-- Carousel item -->
            <div class="owl-wrapper-outer">
              <div class="owl-wrapper" style="width: 5220; left: 0px; display: block; transition: all 800ms ease; transform: translate3d(-522, 0px, 0px);">
              <% @user.items.each do |item| %>
                <div class="owl-item" style="width: 261;">
                  <%= render partial: 'users/carouselitem', locals: {item: item} %>
                </div>
              <% end %>
              </div>
            </div>   
            <div class="owl-controls clickable"><div class="owl-pagination"><div class="owl-page active"><span class=""></span></div><div class="owl-page"><span class=""></span></div></div></div> 
          </div> <!--OWL CAROUSEL-->  
        </div> <!--RECENT ITEMS -->
    </div> <!--ECOMMERCE-->
  </div>

           