config/routes.rb
Rails.application.routes.draw do
  #get 'errors/file_not_found'

  #get 'errors/unprocessable'

  #get 'errors/internal_server_error'

  resources :conversations do 
    resources :messages, only: [:index, :create]
  end
  
  
  resources :offers

  root 'communities#show'

  get '/offers/:id/rejected', :to => 'offers#rejected', as: :offer_rejected
  get '/offers/:id/accepted', :to => 'offers#accepted', as: :offer_accepted
  get '/offers/:id/confirm', :to => 'offers#confirm', as: :offer_confirm

  get '/auth/:provider/callback' => 'users#venmo'
  get '/auth/venmo', as: 'venmo_login'


  get '/communities/search', as: :search
  get '/communities/info', as: :info
  post '/communities/search' => 'communities#set', as: :set

  post '/items' => 'items#search'

  resources :communities do 
    resources :items
  end

  resources :users do
    resources :offers, only: [:index]
    resources :items do 
      resources :offers, only: [:new]
    end
  end

  get '/users/:id/offers/sent' => 'offers#sent', as: :offers_sent
  get '/users/:id/offers/received' => 'offers#received', as: :offers_received

  delete '/users/:user_id/items/:id', to: 'items#destroy', as: :delete_item
  patch '/users/:id' => 'users#update'
  get '/signup' => 'users#new'

  get '/logout', to: 'sessions#destroy', as: :logout
  get '/login', to: 'sessions#new', as: :login
  post '/login' => 'sessions#create'

  get '/about' => 'static_pages#about', as: :about


  #match '/404', to: 'errors#file_not_found', via: :all
  #match '/422', to: 'errors#unprocessable', via: :all
  #match '/500', to: 'errors#internal_server_error', via: :all

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :buyer, :class_name => 'User'
  belongs_to :item
  delegate :seller, to: :item
  has_many :offer_payment_options
  has_many :payment_options, through: :offer_payment_options

  validates :status, inclusion: { in: %w(accepted rejected pending), message: "%{value} is not valid"}

  validate :not_own_item

  def charge_venmo
    note =  "Just bought #{self.item.name} from #{self.seller.name} on CampusBazaar"
    amount = self.offer_price# '-0.20'#
    VenmoWrapper.new.transfer_money_from(buyer,seller,amount,note)
  end

  def self.pending_offers(item_id)
    Item.find(item_id).offers.select{ |offer| offer.status == 'pending'}
  end 

  def settle
    self.status = 'accepted'
    save
    reject_offers(item_id)
  end

  private
    def not_own_item
      if seller.id == buyer.id
        errors.add(:base, "Seller cannot purchase their own listing.")
      end
    end

    def reject_offers(item_id)
      offers = Offer.pending_offers(item_id)
      offers.each do |offer|
        offer.status = 'rejected'
        offer.save
      end 
    end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController

  def new 
    @user = User.find(params[:user])  #seller of the item 
    @item = Item.find(params[:item])  #item the offer is about
  end 

  def create
    params["offer"]["payment_option_ids"] = ["2"] if params["offer"]["payment_option_ids"] == [""]
    offer = Offer.new(offer_params)
    if offer.save
      flash[:notice] = "Offer has been submitted!"
    else
      flash[:notice] = "There was an error with your form"
    end
    redirect_to root_path
  end 


  def show    
    @offer = Offer.find(params[:id])
    @item = @offer.item
  end

  def sent
    @pending_offers = current_user.pending_offers_sent
    # get all pending offers of the current user
    @rejected_offers = current_user.rejected_offers_sent
    # get all rejected offers of the current user
    @accepted_offers = current_user.accepted_offers_sent
    # get all accepted offers of the current user
  end

  def received
    @available_items = current_user.items.select{|item| item.available?}
    @sold_items = current_user.items.reject{|item| item.available?}
    @count = current_user.offers_received.count
  end

  def accepted
    offer = Offer.find(params[:id])

    case params[:payment_method].downcase
    when "venmo"
      transaction_status = offer.charge_venmo.to_sym
    when "cash"
      transaction_status = :cash
    else
      transaction_status = nil
    end

    if transaction_status == :settled || transaction_status == :cash
      offer.settle
    end
    
    flash[:notice] = offer_flash_message(transaction_status, offer)
    redirect_to offers_received_path
  end 

  def rejected
    offer = Offer.find(params[:id])
    offer.status = 'rejected'
    offer.save
    redirect_to offers_received_path
  end 

  def confirm
    @buyer = Offer.find(params[:id]).buyer
    @offer = Offer.find(params[:id])
  end 

  def destroy
    Offer.destroy(params[:id])
    redirect_to offers_sent_path
  end

  private

    def offer_params
      params.require(:offer).permit(:buyer_id, :item_id, :offer_price, :comment, :payment_option_ids => [])
    end

    def offer_flash_message(flag = nil,offer)
      messages = {
        settled: "You have successfully charged #{offer.buyer.name} for #{offer.offer_price}!", 
        pending: "A charge request has been sent to #{offer.buyer.name}. They will need to accept your Venmo charge manually.",
        failed: "Charging #{offer.buyer.name} was unsuccessful. Contact them for more info.",
        cash: "You have agreed to transact with cash. Please contact the buyer to establish a meeting time, etc.",
        error: "Either this offer hasn't specified any payment options, or another error occurred."
      }
      messages[flag] || "Either you or #{offer.buyer.name} has yet to login to Campus Bazaar with Venmo, and we are unable to make this transaction."
    end

end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_offercontent.html.erb
<td><%= link_to offer.seller.name, user_path(offer.seller) %></td>
<td><%= link_to offer.item.name, user_item_path(offer.seller,offer.item) %></td>
<td><%= offer.item.price %></td>
<td><%= offer.offer_price %></td>
<td><% if offer.comment %>
  <%= offer.comment %>
<% end %></td>
<td><%= time_ago_in_words(offer.created_at) %></td>

<td> <% if offer.status == 'pending' %>
<%= link_to "Cancel", offer_path(offer), {:method => 'delete', :class => 'btn btn-danger btn-xs' } %>
<% end %> </td>

app/views/offers/_offercontenthead.html.erb
  <table class="table table-striped table-hover ">
    <thead>
      <tr>
        <th>Seller</th>
        <th>Item Name</th>
        <th>Item Price</th>
        <th>Offer Price</th>
        <th>Offer Comment</th>
        <th>Offer Date</th>
        <th> </th>
      </tr>
    </thead>

app/views/offers/_table_of_offers.html.erb
 <% item.offers.select do |offer|%>

 <tr  id="item<%=offer.id%>">
  <td id="item_name">
    <%= link_to item.name, offer_path(offer)%> 
  </td>
  <td id="buyer_name">
    <%= offer.buyer.name %>
  </td>
  <td id="offer_price">
    $<%= offer.offer_price %>
  </td>
  <td id="comment">
    <%= offer.comment %>
  </td>
  <td id="time">
    <%= time_ago_in_words(offer.created_at) %>
  </td>
  <td id="status">
    <%= offer.status.upcase %>
  </td>
  <% if !(offer.status == 'accepted' || offer.status == 'rejected')%>
  <td><%= link_to("ACCEPT", offer_confirm_path(offer) , class: "accept-button btn btn-success btn-xs", id: "accept-#{offer.id}") %></td>
  <td><a href="/offers/<%= offer.id %>/rejected" class="reject-button btn btn-danger btn-xs" id="reject-<%=offer.id%>">REJECT</a></td>
  <% elsif offer.status == "rejected" && offer.item.available? %>
  <% if offer.item.conversation_exist?(current_user)%>
    <% conversation_id = offer.item.convo_id(current_user)%>
     <td><%= link_to "Contact Seller", conversations_path()  %><td></td>
  <% else %>
    <td><%= link_to "Contact Seller", new_conversation_path({item_id: offer.item.id, user1_id: offer.buyer.id, user2_id: offer.seller.id})  %><td></td>
  <% end %>


  


  <% else %>
  <td></td>
  <td></td>
  <% end %>
</tr>
<% end %>

app/views/offers/_table_of_received.html.erb
<div class="item_table" id="offer<%=item.id%>">
    <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th width="16%">Item</th>
            <th width="10%">From</th>
            <th width="13%">Offer Price</th>
            <th width="16%">Comments</th>
            <th width="13%">Offer Sent</th>
            <th width="10%">Status</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    <%= render :partial => "table_of_offers", locals: {item: item}%>
    </tbody>
    </table>
    </div>

app/views/offers/confirm.html.erb
<div class="container" style="text-align:center;">

  <p>Are you sure you want to sell <%= @offer.item.name %>  to <%= @buyer.name %>? </p>

  <% @offer.payment_options.each do |p_o| %>
    <p><%= link_to "Pay with #{p_o.name.capitalize}", offer_accepted_path(@offer, payment_method: p_o.name) , class: 'btn btn-success' %></p>
  <% end %>

  <%= link_to 'Go back', offer_path(@offer), class: 'btn btn-danger' %>

</div>

app/views/offers/index.html.erb
<div class = 'offers-index'>

<div class= 'offers-sent'>
<a href="http://imgur.com/Bkt0lXA"><img src="http://i.imgur.com/Bkt0lXA.jpg" title="source: imgur.com" /></a><br><br>
<%= link_to('Your Sent Offers', offers_sent_path(current_user), class: 'btn btn-info') %>
</div>

<div class = 'offers-received'>
<a href="http://imgur.com/gCEgJYz"><img src="http://i.imgur.com/gCEgJYz.jpg" title="source: imgur.com" /></a><br><br>
<%= link_to('Your Received Offers', offers_received_path(current_user), class: 'btn btn-info') %>
</div>

</div>

app/views/offers/new.html.erb
<div class="main-block">

  <div class="page-heading-two">
    <div class="container">
      <h2>Make an Offer <span><%= @item.name %></span></h2>
      <div class="clearfix"></div>
    </div>
  </div>

  <div class="container"> 
    <div class="ecommerce">
      <div class="row">
        <div class="col-md-9 col-sm-8 col-md-push-3 col-sm-push-4">
          <div class="shopping-content">
              <div class="row"> 

                <div class="smart-wrap">
                  <div class="smart-forms wrap-3">
                    <h1>Make an Offer for <%= @item.name %></h1>
                    <p><%= form_for(Offer.new) do |f|%></p>
                    <%= f.label :offer_price %>
                    <p><%= f.number_field :offer_price, :value => format("%.2f", @item.price), :step => 0.01 %></p>
                    <%= f.label :comment %>
                    <p><%= f.text_area :comment %></p>
                    <%= f.hidden_field(:buyer_id, value: "#{current_user.id}") %>
                    <%= f.hidden_field(:item_id, value: "#{@item.id}") %>

                    <%= f.collection_check_boxes(:payment_option_ids, PaymentOption.all, :id, :name, class: 'checkbox checkbox-inline')%>
                    <p>(If no payment option selected, cash will be the default.)</p>
                    <%= f.submit 'Submit Offer', class: "btn btn-color" %>
                    <% end %>

                  </div><!-- end .smart-forms section -->
                </div><!-- end .smart-wrap section -->

              </div>
          </div>
        </div> <!--PUSH-4-->
        <div class="col-md-3 col-sm-4 col-md-pull-9 col-sm-pull-8">
          <div class="sidebar">
            <h2>Navigation</h2>
            <ul class="account-nav">
              <li><%= link_to  "Offers Sent", offers_sent_path(current_user) %></li>
              <li><%= link_to "Edit Account", edit_user_path(current_user)%></li>
              <li><%= link_to "Manage Items", user_items_path(current_user)%></li>
            </ul>
          </div>
        </div> <!--PULL-8-->
      </div> <!--ROW-->
    </div>
  </div>
</div>

app/views/offers/received.html.erb
<div class="page-heading-two">
  <div class="container">
    <h2>Offers Received<span></span></h2>
    <div class="clearfix"></div>
  </div>
</div>
<div class="container tables_of_items">
  
  <% if @count > 0 %>
  <h1>Open Items:</h1>
    <div class="all_offered_item_tables">
    <% @available_items.each do |item| %>
      <% if item.offers.count > 0 %>
    <h4><%= link_to item.name, user_item_path(item.community, item)%> </h4>
       <%= render :partial => "table_of_received", locals: {item: item}%>
     <% end %>
    <% end %>
    </div>

  <h1>Sold Items:</h1>
    <div class="all_sold_item_tables">
    <% @sold_items.each do |item| %>
       <%= render :partial => "table_of_received", locals: {item: item}%>
    <% end %>
    </div>
    <% else %>
      You do not currently have any offers on your items.
    <% end %> 
</div>

app/views/offers/sent.html.erb
<div class="page-heading-two">
  <div class="container">
    <h2>Offers Sent<span></span></h2>
    <div class="clearfix"></div>
  </div>
</div>

<div class="container">
  <% if @pending_offers.count > 0 %>
    <h2>Pending Offers Sent</h2>
      <%= render 'offercontenthead' %>
        <tbody>
      <% @pending_offers.each do |offer| %>
        <tr id='offer_<%= offer.id %>'><%= render :partial => "offercontent", locals: {offer: offer} %></tr>
      <% end %>
        </tbody>
      </table> 
    <% else %>
      <h2> You have no PENDING offers</h2><br><br><br>
  <% end %>

  <% if @accepted_offers.count > 0 %>
    <h2>Accepted Offers Sent</h2>
      <%= render 'offercontenthead' %>
        <tbody>
      <% @accepted_offers.each do |offer| %>
        <tr id='offer_<%= offer.id %>'><%= render :partial => "offercontent", locals: {offer: offer} %></tr>
      <% end %>
        </tbody>
      </table> 
  <% end %>

  <% if @rejected_offers.count > 0 %>
    <h2>Rejected Offers Sent</h2>
      <%= render 'offercontenthead' %>
        <tbody>
      <% @rejected_offers.each do |offer| %>
        <tr id='offer_<%= offer.id %>'><%= render :partial => "offercontent", locals: {offer: offer} %></tr>
      <% end %>
        </tbody>
      </table> 
  <% end %>
</div>

app/views/offers/show.html.erb
<div class="col-sm-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2><%= @item.name %></h2>
    </div>
    <div class="panel-body">
      <%= image_tag @item.product.url(:medium), :class => "img-responsive center-block"%>
    </div>
  </div>
</div>

<div class="col-sm-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2> Item Details </h2>
    </div>
    <div class="panel-body">
     <p><h4>List Price: $<%= format("%.2f",@item.price) %></h4></p>
     <p><h4>Condition: <%= @item.condition %></p></h4>
     <p><h4><%= @item.description %></p></h4> 
    </div>
  </div>
</div>

<div class="col-sm-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h2>Offer:</h2>
    </div>
    <div class="panel-body">
      <p> <h4>From: <%= link_to @offer.buyer.name, user_path(@offer.buyer) %></h4></p>
      <p><h4>Offer Price: $<%= format("%.2f",@offer.offer_price) %></h4></p>
      <p><h4>Status: <%= @offer.status.capitalize %></h4></p>
      <% if @offer.comment %>
      <p><h4>Comments: </h4><%= @offer.comment %></p>  
      <% end %>
      <p>Payment Options:</p>
      <ul>
        <% @offer.payment_options.each do |p_o| %>
          <li><%= p_o.name %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<% if @offer.status == "pending" %>
  <div class="btn-group btn-group-justified">
    <%= link_to "Accept", offer_confirm_path, {:class => "btn btn-success"}  %>
    <%= link_to "Contact Buyer", new_message_path(user: @offer.buyer.id, item: @offer.item_id), {:class => "btn btn-warning"}  %>
    <%= link_to "Reject", offer_rejected_path, {:class => "btn btn-danger"} %>
  </div>
<% end %>