config/routes.rb
Rails.application.routes.draw do
  #get 'errors/file_not_found'

  #get 'errors/unprocessable'

  #get 'errors/internal_server_error'

  resources :conversations do 
    resources :messages, only: [:index, :create]
  end
  
  
  resources :offers

  root 'communities#show'

  get '/offers/:id/rejected', :to => 'offers#rejected', as: :offer_rejected
  get '/offers/:id/accepted', :to => 'offers#accepted', as: :offer_accepted
  get '/offers/:id/confirm', :to => 'offers#confirm', as: :offer_confirm

  get '/auth/:provider/callback' => 'users#venmo'
  get '/auth/venmo', as: 'venmo_login'


  get '/communities/search', as: :search
  get '/communities/info', as: :info
  post '/communities/search' => 'communities#set', as: :set

  post '/items' => 'items#search'

  resources :communities do 
    resources :items
  end

  resources :users do
    resources :offers, only: [:index]
    resources :items do 
      resources :offers, only: [:new]
    end
  end

  get '/users/:id/offers/sent' => 'offers#sent', as: :offers_sent
  get '/users/:id/offers/received' => 'offers#received', as: :offers_received

  delete '/users/:user_id/items/:id', to: 'items#destroy', as: :delete_item
  patch '/users/:id' => 'users#update'
  get '/signup' => 'users#new'

  get '/logout', to: 'sessions#destroy', as: :logout
  get '/login', to: 'sessions#new', as: :login
  post '/login' => 'sessions#create'

  get '/about' => 'static_pages#about', as: :about


  #match '/404', to: 'errors#file_not_found', via: :all
  #match '/422', to: 'errors#unprocessable', via: :all
  #match '/500', to: 'errors#internal_server_error', via: :all

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessor :delete_product, :delete_avatar

  belongs_to :seller, :class_name => 'User'
  delegate :community, to: :seller
  has_many :item_categories
  has_many :categories, through: :item_categories
  has_many :offers
  has_many :conversations

  accepts_nested_attributes_for :categories

  validates :name, presence: true

  before_validation {product.clear if delete_product =='1'}

  has_attached_file :product, :styles => { :medium => "300x300#", :thumb => "100x100#" }, :default_url => 'placeholder-product.gif'
  validates_attachment_content_type :product, :content_type => /\Aimage\/.*\Z/

  def self.findselleritems(item)
    user = User.find_by(:id => item.seller.id)
    user.items
  end

  def self.get_items_of_specific_category(items, category_id)
    category = Category.find_by(:id => category_id)
    items.select{ |item| item.categories.include?(category) && item.available? }
  end

  def status
    any_accepted? ? 'sold' : 'available'
  end

  def available?
    self.status == 'available'
  end

  def any_accepted?
    self.offers.any?{|offer| offer.status == 'accepted'}
  end 

  def conversation_exist?(current_user)
    self.conversations.each do |convo|
      if between_seller_and_buyer?(convo, current_user)
        return true 
      end 
    end 
    return false
  end 

  def convo_id(current_user)
    self.conversations.each do |convo|
      if between_seller_and_buyer?(convo, current_user)
        return convo.id
      end 
    end 
  end 

  def prop
    case 
    when self.price < 50.0
      return "p1"
    when self.price < 100.0
      return "p2"
    when self.price < 500.0
      return "p3"
    when self.price < 1000.0
      return "p4"
    else
      return "p5"
    end
  end

  private 
  def between_seller_and_buyer?(convo, current_user)
    (convo.user1 == current_user && convo.user2 == self.seller) || (convo.user2 == current_user && convo.user1 == self.seller)
  end 



end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :authorize

  def index
    @user = User.find(params[:user_id])
    @items = @user.items
  end

  def new
    
  end

  def edit
    @item = Item.find_by(:id => params[:id])
  end

  def update
    @current_user = current_user
    @item = Item.find_by(:id => params[:id])
    if @item.update_attributes(item_params)
      flash[:notice] = "Item successfully updated"
      redirect_to user_item_path(@current_user, @item)
    else 
      flash[:notice]  = "Please update again"
      redirect_to edit_user_item_path(@current_user, @item)
    end
  end

  def search 
    @keyword = params[:keyword]
    @results = Search.for(@keyword, current_user)
  end 

  def create
    item = current_user.items.build(item_params)
    if item.categories.empty?
      item.categories << Category.find_by(name: "Misc")
    end 
    if current_user.save
      redirect_to user_item_path(current_user, current_user.items.last)
      flash[:notice] = "Item created!"
    else
      render 'items/new'
    end
  end

  def show
    @item = Item.find_by(:id => params[:id])
    @category = @item.categories.first
    @selleritems = Item.findselleritems(@item)
  end

  def destroy
    @item = Item.find_by(:id => params[:id])
    @item.product = nil
    @item.save
    if @item.destroy 
      flash[:notice] = "Item Successfully deleted!"
      redirect_to user_items_path
    else
      flash[:notice]  = "Error in deleting"
      redirect_to edit_user_item_path(@current_user, @item)
    end
  end

  private

    def item_params
      params.require(:item).permit(:name,:price,:description,:condition,:product, :delete_product, :category_ids => [])
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_community_item.html.erb
<div class="col-md-4 col-sm-6 itembox" id="<%=item.price%>" data-price="<%= item.prop %>">
  <!-- Shopping items -->
  <div class="shopping-item">
    <!-- Image -->
    <a href="<%= user_item_path(item.seller, :id => item.id) %>"><%= image_tag item.product.url(:medium), :class => "img-responsive"%></a>
    <!-- Shopping item name / Heading -->
    <h4><%= link_to(item.name, user_item_path(item.seller, :id => item.id))%>
      <span class="color pull-right">$<%= format("%.2f", item.price) %></span>
    </h4>
    <h5><%= link_to "Offered by #{item.seller.name}", user_path(item.seller) %></h5>
    <div class="clearfix"></div>
    <!-- Shopping item hover block & link -->
    <div class="item-hover bg-color hidden-xs">
      <%= link_to "Make Offer", new_offer_path({user: item.seller_id, item: item.id}) %>
    </div>
  </div>
</div>

app/views/items/_otheritems.html.erb
<% @selleritems.each do |item| %>

<% end %>

app/views/items/_user_item.html.erb
<div class="col-md-4 col-sm-6">
  <!-- Shopping items -->
  <div class="shopping-item">
    <!-- Image -->
    <a href="<%= user_item_path(item.seller, :id => item.id) %>"><%= image_tag item.product.url(:medium), :class => "img-responsive"%></a>
    <!-- Shopping item name / Heading -->
    <h4><%= link_to(item.name, user_item_path(item.seller, :id => item.id))%>
      <span class="color pull-right">$<%= format("%.2f", item.price) %></span>
    </h4>
    <div class="clearfix"></div>
    <!-- Shopping item hover block & link -->
    <div class="item-hover bg-color hidden-xs">
    <% if @user == current_user %>
      <%= link_to 'Edit Item', edit_user_item_path(current_user, item) %>
    <% end %>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<div class="container">
    <div class="components">
        <div class="col-md-6">
            <%= form_for([current_user, @item]) do |item_form| %>
            <div class="form-group">
                <%= item_form.label :name %>
                <%= item_form.text_field :name, :value => @item.name%>
            </div>
            <div class="form-group">
                <%= item_form.label :price %>
                <%= item_form.number_field :price, :value => @item.price, :step => 0.01 %>
            </div>
            <div class="form-group">
                <%= item_form.label :product %>
                <%= item_form.file_field :product %>
            </div>
            <div class="form-group">
                <%= item_form.label :delete_product_image%>
                <%= item_form.check_box(:delete_product)%>
            </div>
            <div class="form-group">
                <%= item_form.label :description %>
                <%= item_form.text_area :description, :value=> @item.description, class: 'form-control' %>
            </div>
            <div class="form-group">
                <%= item_form.label :condition %>
                <%= item_form.select :condition,['New','Excellent','Good','Acceptable'], :class => 'form-control', :prompt => 'Select One', :value =>  @item.condition %>
            </div>
            <%= link_to 'Delete', delete_item_path(current_user,@item), :method => 'delete', data: {:confirm => 'Are you sure?'}, class: 'btn btn-danger'%>
            <%= item_form.submit 'Update', :class => 'btn btn-info'%>
            <% end %>
            <br>
            <br>
        </div>
    </div>
</div>

app/views/items/index.html.erb
<div class="page-heading-two">
  <div class="container">
    <div id = "welcomeid">
    <h2>Welcome, <%= current_user.name %> </h2>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="container">
  <div class="ecommerce">
    <div class="col-md-11 col-sm-11 col-md-push-1 col-sm-push-1">
      <div class="shopping-content">
        <hr>
        <div class="row">
          <% @items.each do |item| %>
            <%= render partial: 'items/user_item', locals: {item: item} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="page-heading-two">
  <div class="container">
    <h2>Sell an Item <span></span></h2>
    <div class="clearfix"></div>
  </div>
</div>
<div class="container">
    <div class="components">
        <div class="col-md-5 col-md-offset-1 col-sm-push-1">
            <%= form_for([current_user, Item.new]) do |f| %>
            <%= f.hidden_field :seller_id, :value => current_user.id %>
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name %>
                What are you selling?
            </div>
            <div class="form-group">
                <%= f.label :price %>&nbsp;&nbsp;
                <%= f.number_field :price, :step => 0.01, maxlength: "3" %>
                (A suggested price)                
            </div>
            
            <div class="form-group col-md-6" style="height:100%">
                <%= f.label :description %>
                <%= f.text_area :description, class: 'form-control' %>
            </div>

            <div class="form-group col-md-6">
                <ul style="list-style-type:none">
                <%= f.collection_check_boxes :category_ids, Category.all, :id, :name  do |b|%>
                    <li><%= b.check_box %>&nbsp;&nbsp;&nbsp;<%= b.label %></li>
                <% end %>
                </ul>
            </div>
            <div class="form-group">
                <%= f.label :condition %>
                <%= f.select :condition,['New','Excellent','Good','Acceptable'], :class => 'form-control', :prompt => 'Select One'%>
            </div>
            <%= f.submit 'Add Item', :class => 'btn btn-info'%>
            
            <br>
            <br>
        </div>
        <div class="col-md-5 col-md-push-1 col-sm-push-1">
            <div class="upload-preview">
                <%=image_tag 'placeholder-product.gif'%>
            </div>
            <div class="form-group">
                <%= f.label :product, "Item Preview" %>
                <%= f.file_field :product, class: 'file'%>
            </div>
        </div>
        <% end %>
    </div>
</div>
<br><br><br>

app/views/items/search.html.erb
<div class="main-block">
  <div class="page-heading-two">
    <div class="container">
      <h2>Search Results <span><%= @keyword %></span></h2>
      <div class="clearfix"></div>
    </div>
  </div>
  <div class="container">
    <div class="ecommerce">
      <div class="row">
        <div class="col-md-9 col-sm-8 col-md-push-3 col-sm-push-4">
          <div class="shopping-content">
            <div class="row">

              <% if @results.size > 0 %>


              <% @results.each do |item| %>
              <%= render partial: 'items/community_item', locals: {item: item} %>
              <% end %>



              <% else %>
              <h4>No results found</h4>
              <% end %>
            </div>
          </div>
        </div><!-- PUSH-4 -->
        <div class="col-md-3 col-sm-4 col-md-pull-9 col-sm-pull-8">
          <div class="sidebar">
            <h2>Navigation</h2>
            <ul class="account-nav">
              <li><%= link_to  "Your Community", root_path %></li>
              <li><%= link_to "Edit Account", edit_user_path(current_user)%></li>
              <li><%= link_to "Manage Items", user_items_path(current_user)%></li>
            </ul>
          </div>
        </div> <!--PULL-8-->
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div align = 'right' style= 'margin-right: 2%;'>
<% if (current_user.id == @item.seller_id)%>
<%= link_to 'Edit Item', edit_user_item_path(current_user, @item), class: 'btn btn-info'%>
<%end%>
</div>
<div class="container">
  <div class="ecommerce">
    <div class="row">
      <div class="col-md-9 col-sm-8 col-md-push-3 col-sm-push-4">
        <div class="shoppoing-content">
          <div class="shopping-single">
            <div class="col-md-4 col-sm-6">
              <%= image_tag @item.product.url(:medium) %>
            </div>
            <div class="col-md-6 col-sm-4 col-md-push-1 col-sm-push-1">
              <h4><%= @item.name %></h4>
              <p><%= @item.description %></p>
              <div class="table-responsive">
                <table class="table table-bordered sitem-table">
                  <tbody>
                    <% unless @item.seller == current_user %>
                      <tr>
                        <th>Sold By :</th>
                        <td><%= link_to @item.seller.name, user_path(@item.seller) %></td>
                      </tr>
                    <% end %>
                    <tr>
                      <th>Name :</th>
                      <td><%= @item.name %></td>
                    </tr>
                    <tr>
                      <th>List Price :</th>
                      <td>$<%= format("%.2f", @item.price) %></td>
                    </tr>
                    <tr>
                      <th>Condition :</th>
                      <td><%= @item.condition %></td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <% unless @item.seller == current_user %>
                <%= link_to "Make Offer", new_offer_path({user: @item.seller_id, item: @item.id}), {class: 'btn btn-danger'}  %>
                <% if @item.conversation_exist?(current_user)%>
                  <% conversation_id = @item.convo_id(current_user)%>
                  <%= link_to "Contact Seller", conversations_path(), class: 'btn btn-default'  %>
                <% else %>
                  <%= link_to "Contact Seller", new_conversation_path({item_id: @item.id, user1_id: current_user.id, user2_id: @item.seller.id}), class: 'btn btn-default'  %>
                <% end %>
              <% end %>
            </div>            
          </div>
        </div>
      </div>
      <div class="col-md-3 col-sm-4 col-md-pull-9 col-sm-pull-8">
        <div class="sidebar">
          <div class="s-widget">
            <h3>Other Items From: <%= @item.seller.name %></h3>
            <% @selleritems.each do |item| %>
              <div class="sw-content">
              <% if item != @item %>
                <a href="<%= user_item_path(item.seller, :id => item.id) %>"><%= image_tag item.product.url(:medium), :class => "img-responsive"%>
                </a>
                <a href="<%= user_item_path(item.seller, :id => item.id) %>">
                  <h4><%= item.name %></h4>
                </a>  
                <br>
                <span class="sw-price">$<%= format("%.2f", item.price) %></span>   
                <div class="clearfix"></div>           
              </div>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div> 
</div>