config/routes.rb
Rails.application.routes.draw do
  #get 'errors/file_not_found'

  #get 'errors/unprocessable'

  #get 'errors/internal_server_error'

  resources :conversations do 
    resources :messages, only: [:index, :create]
  end
  
  
  resources :offers

  root 'communities#show'

  get '/offers/:id/rejected', :to => 'offers#rejected', as: :offer_rejected
  get '/offers/:id/accepted', :to => 'offers#accepted', as: :offer_accepted
  get '/offers/:id/confirm', :to => 'offers#confirm', as: :offer_confirm

  get '/auth/:provider/callback' => 'users#venmo'
  get '/auth/venmo', as: 'venmo_login'


  get '/communities/search', as: :search
  get '/communities/info', as: :info
  post '/communities/search' => 'communities#set', as: :set

  post '/items' => 'items#search'

  resources :communities do 
    resources :items
  end

  resources :users do
    resources :offers, only: [:index]
    resources :items do 
      resources :offers, only: [:new]
    end
  end

  get '/users/:id/offers/sent' => 'offers#sent', as: :offers_sent
  get '/users/:id/offers/received' => 'offers#received', as: :offers_received

  delete '/users/:user_id/items/:id', to: 'items#destroy', as: :delete_item
  patch '/users/:id' => 'users#update'
  get '/signup' => 'users#new'

  get '/logout', to: 'sessions#destroy', as: :logout
  get '/login', to: 'sessions#new', as: :login
  post '/login' => 'sessions#create'

  get '/about' => 'static_pages#about', as: :about


  #match '/404', to: 'errors#file_not_found', via: :all
  #match '/422', to: 'errors#unprocessable', via: :all
  #match '/500', to: 'errors#internal_server_error', via: :all

end

app/views/layouts/_footer.html.erb
<div class="container">
  <!-- Footer Content -->
    <!-- Paragraph -->
    <p class="pull-left">Copyright © 2015 - <a href="#">CampusBazaar</a></p>
    <ul class="list-inline pull-right">
      <!-- List -->
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to("About this Project", about_path) %></li>
    </ul>
    <center>
      <div class="footer-text">Made with <i class="fa fa-heart"></i> at <span id = "slash">//</span> <a href="http://www.flatironschool.com" target="blank" style = "text-decoration: none;">Flatiron School.</a>
      </div>
    <center>
    <!-- Clearfix -->
    <div class="clearfix"></div>
</div>

app/views/layouts/_header.html.erb
<title>CampusBazaar</title>
<%= stylesheet_link_tag    'application', media: 'all' %>
<%= javascript_include_tag 'application' %>
<%= csrf_meta_tags %>
<%= analytics_init if Rails.env.production? %>

app/views/layouts/_navbar.html.erb
<div class="top-bar">
  <div class="container">
    <div class="tb-contact pull-left">
      <!-- Email -->
      <i class="fa fa-envelope color"></i> &nbsp; <a href="mailto:thecampusbazaar@gmail.com" target="_blank">thecampusbazaar@gmail.com</a>
      &nbsp;&nbsp;  
    </div>
    <div class="tb-social pull-right">
      <div class="brand-bg text-right">
        <!-- Brand Icons -->
        <a href="https://www.facebook.com/theCampusBazaar" target="_blank" class="facebook"><i class="fa fa-facebook square-2 rounded-1"></i></a>
        <a href="https://twitter.com/theCampusBazaar" target="_blank" class="twitter"><i class="fa fa-twitter square-2 rounded-1"></i></a>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>  
</div>

<div class="header-2 bg-grey" >
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <!-- Logo section -->
        <div class="logo">
          <h1><%= link_to 'CampusBazaar', root_path %></h1>
        </div>
      </div>
      <div class="col-md-8">  
              <!-- Navigation starts.  -->
        <div class="navy">    
          <ul>
          <% if current_user %>
            <!-- Main menu -->
            <li class="has-sub"><span class="submenu-button"></span><a href="">Menu</a>
              <!-- Submenu -->
              <ul>
                <li><%= link_to  "Edit Your Account", user_path(current_user) %></li>
                <li ><%= link_to("Messages", conversations_path) %></li>
                <li ><%= link_to('Sell an Item', new_user_item_path(:user_id => current_user.id)) %> </li>
                <li ><%= link_to('Manage Your Items', user_items_path(:user_id => current_user.id)) %> </li>
                <!-- 2nd Level sub menu -->
                 <% if current_user.seller? %>
                <li class="has-sub"><span class="submenu-button"></span>
                  <a href="#">Offers</a>
                  <ul>
                    <li><%= link_to('Offers Sent', offers_sent_path(current_user))%></li>
                    <li><%= link_to('Offers Received', offers_received_path(current_user))%></li>
                  </ul>
                </li>
                <% elsif current_user.buyer? %>
                  <li ><%= link_to('Offers Sent', offers_sent_path(current_user)) %> </li>
                <% end %>

              </ul>
            </li>              
            <li><%= link_to(" About this Project", about_path) %></li>
            <% end %>
        <% if current_user %>
          <li class="pull-right"><%= link_to "Logout", '/logout' %></li>
          <li class="pull-right"><%= link_to "|", '/' %></li>
          <li class="pull-right"><%= link_to "Signed in as #{current_user.name}", user_path(current_user) %></li>
          <% else %>
          <li class="pull-right"><%= link_to 'Login', '/login' %></li>
          <li class="pull-right"><%= link_to "|", '/' %></li>
          <li class="pull-right"><%= link_to 'Signup', '/signup' %></li>
        <% end %>
          </ul>
        </div>              
         <!-- Navigation ends -->        
      </div>
      <div class="col-md-1">
        <!-- Search section -->
        <div class="head-search pull-right">
          <a href="#" class="b-dropdown"><i class="fa fa-search square-2 rounded-1 bg-color white"></i></a>
          <div class="b-dropdown-block">
            <%= form_tag('/items') do %> 
               <div>
               <%= text_field_tag :keyword%>  
               <%= submit_tag 'Search' %> 
               </div>
            <% end -%>



            <%#= form_tag "/items", :role => "form" do %>
              <!-- <div class="input-group"> -->
              <%#= text_field_tag :keyword, nil, :placeholder => "Search Here", :class =>"form-control", :name =>"keyword", :id =>"keyword" %>
              <!-- </div>
              <span class="input-group-btn"> -->
              <%#= submit_tag 'Search', :class => "btn btn-color btn-m", :name => "commit"%>
              <!-- </span> -->
            <%# end %>
          </div>
        </div>
        <!-- Search section ends -->
        <div class="clearfix"></div>        
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= render partial: 'layouts/header'%>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body style="PADDING-TOP: 1px">
<div id="wrapper">
<div id="content">
<div class="outer">
  <%= render partial: 'layouts/navbar'%>
  <% if notice %>
    <div class="alert alert-success"><%= notice %></div>
  <% end %>
  <div class="main-block">
    <%= yield %>
  </div>

</div>

  <span class="totop" style="display: block;"><a href="#"><i class="fa fa-angle-up bg-grey"></i></a></span>
  </div>
  <div id="footer">
  <%= render 'layouts/footer' %>
  </div>
</div>
</body>
</html>


<!--  -->